### ISSUE TITLE
action continues to fail

### ISSUE THREAD

**Issue by panva** [JasonEtco/is-sponsor-label-action#16]
```
Error: Cannot read property 'id' of null
✖  fatal     TypeError: Cannot read property 'id' of null 
    at /lib/user-is-sponsor.js:45:41
    at Array.find (<anonymous>)
    at makeRequest (/lib/user-is-sponsor.js:45:15)
```

<img width="1315" alt="Screenshot 2020-11-15 at 13 27 25" src="https://user-images.githubusercontent.com/241506/99184870-6cb61b80-2746-11eb-91a6-a299d3946e42.png">

I'd be happy to provide more details when requested.

**Comment by panva** [comment]
Possibly because of private sponsors?
