### ISSUE TITLE
Add support for pull_request_target

### ISSUE THREAD

**Issue by crazy-max** [JasonEtco/is-sponsor-label-action#22]
Hi @JasonEtco,

[GITHUB_TOKEN secrets are not passed to the runner when a workflow is triggered from a forked repository](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories-2) so this action does not work for pull request unfortunately:

```text
⬤  debug     Making label [:sparkling_heart: sponsor]
⬤  debug     Author is a sponsor! Adding the [:sparkling_heart: sponsor] label!
Error: Resource not accessible by integration
✖  fatal     HttpError: Resource not accessible by integration 
    at /home/runner/work/_actions/JasonEtco/is-sponsor-label-action/024ac24f8b170abce078cad4ee748852369853c8/dist/index.js:4602:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Toolkit.run.event (/home/runner/work/_actions/JasonEtco/is-sponsor-label-action/024ac24f8b170abce078cad4ee748852369853c8/dist/index.js:28:3)
```

So it would be nice to handle the [`pull_request_target`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) event to be able to use this action in a PR from fork:

```text
✖  error     Event `pull_request_target.reopened` is not supported by this action.
```

Thanks!

**Comment by crazy-max** [comment]
Oups sorry dup of #9
