### ISSUE TITLE
bug: Resource not accessible by integration

### ISSUE THREAD

**Issue by ocavue** [JasonEtco/is-sponsor-label-action#28]
When we use `JasonEtco/is-sponsor-label-action`, we get this error:

```
Run JasonEtco/is-sponsor-label-action@v1
Error: Resource not accessible by integration
✖  fatal     GraphqlError: Resource not accessible by integration 
    at /home/runner/work/_actions/JasonEtco/is-sponsor-label-action/v1/dist/index.js:2463:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async makeRequest (/home/runner/work/_actions/JasonEtco/is-sponsor-label-action/v1/dist/index.js:150:20)
    at async Toolkit.run.event (/home/runner/work/_actions/JasonEtco/is-sponsor-label-action/v1/dist/index.js:20:21)
```

https://github.com/remirror/remirror/pull/1210/checks?check_run_id=3511169860

This action works pretty well the whole time and starts to show this error since yesterday.

**Comment by lissy93** [comment]
+1 - Your action is awesome, and has worked perfectly for me up until Wednesday.
But I now get the same error as OP, and it causes my pull requests to [fail](https://github.com/Lissy93/dashy/runs/3518461564).

```
Error: Resource not accessible by integration
✖  fatal     GraphqlError: Resource not accessible by integration 
    at /home/runner/work/_actions/JasonEtco/is-sponsor-label-action/v1/dist/index.js:2463:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async makeRequest (/home/runner/work/_actions/JasonEtco/is-sponsor-label-action/v1/dist/index.js:150:20)
    at async Toolkit.run.event (/home/runner/work/_actions/JasonEtco/is-sponsor-label-action/v1/dist/index.js:20:21)
0s
```

For reference, here are the [complete logs](https://pipelines.actions.githubusercontent.com/w6jiW369VLnTRNX4yl6jNyAzyyWAGezZT9hWtU883HWxYABVPP/_apis/pipelines/1/runs/1653/signedlogcontent/3?urlExpires=2021-09-05T16%3A32%3A03.2320915Z&urlSigningMethod=HMACV1&urlSignature=vyhyYU%2BpmX%2FGirBdVmSUT8ELEUq41Q%2Fo8vyurFJ9VJc%3D). And this is my [workflow file](https://github.com/Lissy93/dashy/actions/runs/1203448591/workflow).

I guess it's an external change in an API, and not directly related to this action. But it would be great to have an update sometime, so that it can work again. Thank you @JasonEtco for all your work in developing and maintaining  is-sponsor-label-action, it's been really useful :)

**Comment by tomkerkhove** [comment]
I have the same issue indeed

**Comment by lissy93** [comment]
@JasonEtco - Any update on this?
 I have tried to look into this, but am quite new with GH Actions, so am unsure what the solution is.

**Comment by dansiegel** [comment]
this isn't a bug for @JasonEtco to fix. It is being caused by a bug that the GitHub team accidently introduced. The team knows about the issue and has prioritized it for fix. I have no clue what that means in terms of when we can expect it to be resolved, but I would assume once they've fixed it we'll start seeing all new PRs and Issues getting the label properly again.

**Comment by kdeldycke** [comment]
I guess this was fixed in #30 by @cheshire137.

I tried to reused this PR in https://github.com/kdeldycke/workflows/commit/dfa9ffbbf268c5cfba9143b4820a172f8c3699f2 but it failed:
```
> Run cheshire137/is-sponsor-label-action@e57c7e5adc854fdae4a39062c61e629f614160d5
Error: File not found: '/home/runner/work/_actions/cheshire137/is-sponsor-label-action/e57c7e5adc854fdae4a39062c61e629f614160d5/dist/index.js'
```

I guess this action need special care to be distributed and can't be reused as-is.

**Comment by cheshire137** [comment]
Uh-oh, did I commit some hardcoded `cheshire137` in my fix? That was unintentional if so!

**Comment by kdeldycke** [comment]
> Uh-oh, did I commit some hardcoded `cheshire137` in my fix? That was unintentional if so!

Oh no no no! 😅 It's just the way the [`v1.1.3` tag](https://github.com/JasonEtco/is-sponsor-label-action/tree/v1.1.3) is at odds with other releases, as the former has its `index.js` located in a `dist` subfolder, while others don't.

**Comment by FrightRisk** [comment]
We have this issue also. It is causing an error in our build process:

![image](https://user-images.githubusercontent.com/37218136/166518135-8758261a-b0d3-4f69-bb3c-464c8cd98cfd.png)

**Comment by moul** [comment]
Wdyt about having by default or using an option, a way to make the PR not failing if the resource is (temporarily?) not accessible?

**Comment by fatihyildizhan** [comment]
Hi, I have the same problem.

**Comment by AnalogJ** [comment]
Has this issue been fixed? I had to disable this GH workflow in my repos, and I'd like to re-enable them
